name: kumchat
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.20.1"
  provider:
  google_sign_in:
  firebase_database:
  path:
  path_provider:
  flutter_custom_clippers:
  cached_network_image: ^2.3.3
  firebase_core: "^0.7.0"
  # flushbar:
  country_pickers:
  intl:
  firebase_storage:
  image_cropper:
  image_picker:
  font_awesome_flutter: ^9.1.0
  flutter_local_notifications: 
  scoped_model: ^1.0.1
  rxdart:
  http:
  emoji_picker_flutter: ^1.0.6
  video_player:
  flutter_downloader:
  # flutter_gradients:
  url_launcher:
  share:
  video_thumbnail: ^0.3.3
  #just_audio:
  cupertino_icons: ^1.0.3
  story_view: ^0.12.3
  camera:
  agora_rtc_engine: ^4.0.2
  ntp:
  localstorage:
  local_auth:
  contacts_service:
  fluttertoast:
  firebase_messaging: ^8.0.0-dev.14
  shared_preferences:
  flutter_secure_storage:
  crypto:
  encrypt:
  mime:
  cloud_firestore:
  photo_view:
  giphy_picker:
  package_info:
  app_review:
  rating_dialog:
  permission_handler: ^5.1.0+2
  file_picker_cross: ^3.1.1
  flutter_sound: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/flags/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope-regular.otf
        - asset: assets/fonts/manrope-bold.otf
          weight: 700
        - asset: assets/fonts/manrope-extrabold.otf
          weight: 800
        - asset: assets/fonts/manrope-semibold.otf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
